"""Added column to house table

Revision ID: aedd5a8d9579
Revises: 71a2f3bc225f
Create Date: 2024-06-11 20:11:15.714533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aedd5a8d9579'
down_revision: Union[str, None] = '71a2f3bc225f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('successfully_attacked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'successfully_attacked')
    # ### end Alembic commands ###
